# Generated by Django 4.2.6 on 2023-12-03 17:11

import core.validators
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Course name')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='HomeRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
            },
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(db_index=True, max_length=400, verbose_name='Title')),
                ('body', models.TextField(verbose_name='body')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='homework/', validators=[core.validators.check_file_extension], verbose_name='attachment')),
                ('deadline_time', models.DateField(verbose_name='deadline time')),
            ],
            options={
                'verbose_name': 'Home work',
                'verbose_name_plural': 'home works',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='description')),
                ('landline_number', models.CharField(max_length=11, validators=[core.validators.check_landline_number])),
                ('address', models.TextField(verbose_name='address')),
                ('location', django.contrib.gis.db.models.fields.GeometryField(geography=True, srid=4326, verbose_name='location')),
            ],
            options={
                'verbose_name': 'school',
                'verbose_name_plural': 'schools',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='Title')),
                ('body', models.TextField(verbose_name='body')),
                ('homeroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.homeroom', verbose_name='homeroom')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='HomeWorkResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('body', models.TextField(verbose_name='body')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='homework/response/', validators=[core.validators.check_file_extension], verbose_name='attachment')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.homework', verbose_name='homework')),
            ],
            options={
                'verbose_name': 'homework Response',
                'verbose_name_plural': 'homework Response',
            },
        ),
    ]
