# Generated by Django 4.2.6 on 2023-12-03 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkresponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='student'),
        ),
        migrations.AddField(
            model_name='homework',
            name='homeroom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.homeroom', verbose_name='homeroom'),
        ),
        migrations.AddField(
            model_name='homeroom',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course', verbose_name='course'),
        ),
        migrations.AddField(
            model_name='homeroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school'),
        ),
        migrations.AddField(
            model_name='homeroom',
            name='students',
            field=models.ManyToManyField(related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='students'),
        ),
        migrations.AddField(
            model_name='homeroom',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='teacher'),
        ),
    ]
